[project]
name = "jane-street-problems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.14.10",
    "numpy>=2.3.1",
    "quarto>=0.1.0",
    "sympy>=1.14.0",
]
